language: php
sudo: false

php:
  - 7.1

env:
  - SYMFONY_VERSION=3.3.*

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer install --dev --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpcs ./ -p --standard=./ruleset.xml
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
  email:
    - bukashk0zzz@gmail.com
